name: Feature Request
description: Suggest a new idea for Orion
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: What would you like to see added or changed?
      placeholder: "Describe the feature..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important or useful?
      placeholder: "Because..."
